name: better_phenikaa_schedule
description: Better Phenikaa App - lịch học và lịch thi cho sinh viên Phenikaa University.
publish_to: none
version: 1.0.0+26
environment:
  sdk: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: 6.1.5
  home_widget: 0.10.0
  html: 0.15.7
  shared_preferences: 2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: 11.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tien_mon_premium/app_backgrounds/
    - assets/tien_mon_premium/widget_overview/

  fonts:
    - family: MinecraftCustom
      fonts:
        - asset: assets/fonts/minecraft.ttf
    - family: FzCoTrang
      fonts:
        - asset: assets/tien_mon_premium/fonts/FzCoTrang.ttf
