#!/usr/bin/env python3
"""Generate Flutter and native catalogs from the approved, verbatim U1–U18 text."""

import json
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tool" / "assistant_pack_texts.json"
PACKS = ("normal", "serious", "playful", "affectionate",
         "flirtatious", "academic", "blunt", "cultivation")

data = json.loads(SOURCE.read_text())
assert set(data) == set(PACKS)
assert all(set(rows) == {f"U{i}" for i in range(1, 19)} for rows in data.values())

def dart_quote(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'"

dart = [
    "// Generated by tool/generate_assistant_catalog.py. Edit the JSON source.",
    "const assistantCatalog = <String, Map<int, String>>{",
]
kt = [
    "package vn.edu.phenikaa.better_phenikaa_schedule",
    "",
    "/** Generated by tool/generate_assistant_catalog.py. Edit the JSON source. */",
    "internal object AssistantCatalog {",
    "    val texts: Map<String, Map<Int, String>> = mapOf(",
]
for name in PACKS:
    dart.append(f"  '{name}': <int, String>{{")
    kt.append(f'        "{name}" to mapOf(')
    for index in range(1, 19):
        value = data[name][f"U{index}"]
        chunks = textwrap.wrap(value, 58, break_long_words=False,
                               break_on_hyphens=False, drop_whitespace=False)
        if len(chunks) == 1:
            dart.append(f"    {index}: {dart_quote(value)},")
        else:
            dart.append(f"    {index}:")
            for chunk in chunks:
                dart.append(f"        {dart_quote(chunk)}")
            dart[-1] += ","
        kt.append(f"            {index} to {json.dumps(value, ensure_ascii=False)},")
    dart.append("  },")
    kt.append("        ),")
dart.extend(["};", ""])
kt.extend(["    )", "}", ""])

(ROOT / "lib/features/tro_li/assistant_catalog.dart").write_text(
    "\n".join(dart), encoding="utf-8"
)
(ROOT / "android/app/src/main/kotlin/vn/edu/phenikaa/better_phenikaa_schedule/AssistantCatalog.kt").write_text(
    "\n".join(kt), encoding="utf-8"
)
